version: '3.3'
services:

  mysql:
    platform: linux/x86_64
    image: mysql:5.7 # MySQLのバージョン指定
    container_name: db-for-go

    # MySQLの設定値を指定
    command: 
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --sql-mode=ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    
    # コンテナ内で使用する環境変数の値を指定
    environment:
        MYSQL_ROOT_USER: ${ROOTUSER} # MySQLのルートユーザー名
        MYSQL_ROOT_PASSWORD: ${ROOTPASS} # MySQLのルートユーザーのパスワード
        MYSQL_DATABASE: ${DATABASE} # MySQLに用意されている初期DB名
        MYSQL_USER: ${USERNAME} # MySQLのユーザー名
        MYSQL_PASSWORD: ${USERPASS} # MySQLのユーザーパスワード
        TZ: 'Asia/Tokyo'

    # コンテナの3306番ポートをローカルの3306番ポートに接続する
    ports:
        - "3306:3306"

    # コンテナ内にあるMySQLに格納するデータを永続化させるために使用するボリュームを指定
    volumes:
        - db-volume:/var/lib/mysql

# ボリュームの作成
volumes:
  db-volume:
